{{ config(materialized='view') }}

SELECT
    TRIM(ENCOUNTER_ID) AS ENCOUNTER_ID,
    TRIM(PATIENT_ID) AS PATIENT_ID,
    TRIM(PROVIDER_ID) AS PROVIDER_ID,
    AGE,
    START_DATE,
    TRIM(ENCOUNTER_TYPE) AS ENCOUNTER_TYPE,
    END_DATE,
    UPDATED_AT
FROM {{ source('raw', 'ENCOUNTERS') }}