{{ config(materialized='view') }}

SELECT
    TRIM(ENCOUNTER_ID) AS ENCOUNTER_ID,
    TRIM(PROCEDURE_CODE) AS PROCEDURE_CODE,
    TRIM(PROCEDURE_DESCRIPTION) AS PROCEDURE_DESCRIPTION,
    PROCEDURE_DATE
FROM {{ source('raw', 'PROCEDURES') }}