{{ config(materialized='view') }}

SELECT
    TRIM(ENCOUNTER_ID) AS ENCOUNTER_ID,
    TRIM(DIAGNOSIS_CODE) AS DIAGNOSIS_CODE,
    TRIM(DIAGNOSIS_DESCRIPTION) AS DIAGNOSIS_DESCRIPTION,
    DIAGNOSIS_RANK
FROM {{ source('raw', 'DIAGNOSIS') }}