{{ config(materialized='view') }}

SELECT
    FACILITY_ID,
    TRIM(FIRST_NAME) AS FIRST_NAME,
    TRIM(LAST_NAME) AS LAST_NAME,
    NPI,
    TRIM(PROVIDER_ID) AS PROVIDER_ID,
    TRIM(SPECIALTY) AS SPECIALTY,
    TRY_TO_DATE(UPDATED_AT, 'DD/MM/YY') AS UPDATED_AT
FROM {{ source('raw', 'PROVIDERS') }}